version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules