apiVersion: v1
kind: Service
metadata:
  name: edukita-frontend-service
spec:
  selector:
    app: edukita-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer